### PR TITLE
Arguments for `add_argument` are now shown in separated lines

### PR DESCRIPTION
**Pull request by rodrigo-morales-1**
I've mainly created this pull request to improve the readability of the source code.

### CODE REVIEW

**Review by musically-ut — CHANGES_REQUESTED** [review]
Is this compliant with `black`? 

I'd prefer to keep the default out-of-box behavior of `black` for the source code as much as possible.

**Comment by rodrigo-morales-1** [comment]
To be honest, I have never used `black` before but I have some time to look into this formatter. I will read the documentation and let you know whether the changes introduced by this pull request are correctly formatted according to `black`.

**Comment by rodrigo-morales-1** [comment]
@musically-ut I've looked into this and my changes are not compliant to the Black formatter, so I think it would be appropiate to close this pull request.

It is worth mentioning that I created this pull request because I noticed that there were some `add_argument` rules that were wrote in separated lines (see below)

https://github.com/Networks-Learning/stackexchange-dump-to-postgres/blob/49d8358a83bb573c63c2715b122afb2fca98376c/load_into_pg.py#L317-L322

https://github.com/Networks-Learning/stackexchange-dump-to-postgres/blob/49d8358a83bb573c63c2715b122afb2fca98376c/load_into_pg.py#L338-L344

while others weren't

https://github.com/Networks-Learning/stackexchange-dump-to-postgres/blob/49d8358a83bb573c63c2715b122afb2fca98376c/load_into_pg.py#L324-L326

**Comment by musically-ut** [comment]
Yup, I'd understood the intentions behind it. :) 

However, when it comes to code-formatting, I'd prefer to have effortless conformity rather than meticulous consistency. 🤷

**Comment by rodrigo-morales-1** [comment]
I will consider that in future pull requests. Thanks for the advice! 👍

**Pull request closed without merging**
