### PR TITLE
Fixes Issue #1 - adds support for PostLinks and Comments

### PR DESCRIPTION
**Pull request by fattymelt**
Update script with basic support for PostLink and Comment objects. Updated README.

### CODE REVIEW

**Comment by fattymelt** [comment]
Sorry, I meant for

**Comment by musically-ut** [comment]
LGTM. 

Did you accidentally close it or did you mean to add more commits?

(Reopening the PR).

**Comment by fattymelt** [comment]
I closed it on purpose, only because I meant to create the PR on our fork and not here, but you're obviously welcome to add this bit into your repo.

**Review by musically-ut — APPROVED** [review]
Thanks!

**Pull request merged**
