### PR TITLE
2020 Update

### PR DESCRIPTION
**Pull request by bersace**
Hi,

Thanks for this great project :-)

I found some rough edge and though I could polish the project. Here is my contribution.

- Update dependencies, this allows to use wheel.
- Fix confusion between libarchive and libarchive-c.
- Provide a quickstart to load stackexchange in a database in 3 commands.

What do you think of this ?

### CODE REVIEW

**Comment by bersace** [comment]
cc @madtibo

**Comment by musically-ut** [comment]
The changes look good. I'll want to try it out once with a new venv to make sure that nothing silly breaks and merge it in.

re: the documentation; I would want to keep the explicit list of tables instead of showing just one for the sake of completeness. Could you make that change @bersace? 

Thanks!

**Comment by bersace** [comment]
Hi @musically-ut thanks for the review !

You're right, I updated the README to document supported tables by `load_into_pg.py`.

Feel free to nitpick :-)

**Comment by bersace** [comment]
:up:

**Comment by musically-ut** [comment]
Thanks! 💯

**Pull request merged**
